### ISSUE TITLE
a small question to solve

### ISSUE THREAD

**Issue by sukong19** [vinits5/masknet#1]
Hello, thank you for providing such a complete and excellent code.I have successfully run the code on the my computer.
But I have a question that needs to be resolved--what do the files 'sd_01-04_noise_pointlk.pth'  under the path '\masknet-main-try\pretrained\exp_pointnetlk\models'  represent, and how they are created？
Looking forward to your answer☺☻

**Comment by vinits5** [comment]
Hello, thank you for your interest in our work and appreciation. 
"sd_01-04_noise_pointlk.pth" are pre-trained models of PointNetLK network for point cloud registration in the presence of Gaussian noise in the source point clouds at the time of training. "sd" stands for the value of standard deviation (std. dev.) for Gaussian noise and the value 01-04 represents the value of std. dev. from 0.01 to 0.04

**Comment by sukong19** [comment]
Thank you for your answer and wish you more progress in scientific research.
